// The order defines priority, the thunderstorm most important - seaicing least important
export const knownWarningTypes = [
  // english event codes
  'Strong wind warning',
  'Strong wind and poor visibility warning',
  'Heavy precipitation warning',
  'Thunderstorm warning',
  'Low snow avalanche danger',
  'Moderate snow avalanche danger',
  'Considerable snow avalanche danger',
  'High snow avalanche danger',
  'Very high snow avalanche danger',
  'Hail warning',
  'Flash flood warning',
  'Flood warning',
  'Heavy snowfall warning',
  'Heavy snowfall and strong wind warning',
  'High daytime temperature warning',
  'High nighttime temperature warning',
  'Low temperature warning',
  'Early frost warning',
  'Late frost warning',
  'Fog warning',
  'Mudflow warning',
  'Landslide advisory',
  'Landslide warning',
  'Air quality warning',
  'High UV radiation warning',
  'Very high UV radiation warning',
  'Extreme UV radiation warning',
  'Sea storm warning',

  // georgian event codes
  'გაფრთხილება ძლიერი ქარის შესახებ',
  'გაფრთხილება ძლიერი ქარისა და ხილვადობის გაუარესების შესახებ',
  'გაფრთხილება ძლიერი ნალექების შესახებ',
  'გაფრთხილება ძლიერი ნალექებისა და ელჭექის შესახებ',
  'ზვავსაშიშროების დაბალი დონე',
  'ზვავსაშიშროების საშუალო დონე',
  'ზვავსაშიშროების საშუალოზე მაღალი დონე',
  'ზვავსაშიშროების მაღალი დონე',
  'ზვავსაშიშროების ძალიან მაღალი დონე',
  'გაფრთხილება სეტყვის შესახებ',
  'გაფრთხილება წყალმოვარდნის შესახებ',
  'გაფრთხილება წყალდიდობის შესახებ',
  'გაფრთხილება ძლიერი თოვის შესახებ',
  'გაფრთხილება ძლიერი თოვის და ძლიერი ქარის შესახებ',
  'გაფრთხილება დღის მაღალი ტემპერატურის შესახებ',
  'გაფრთხილება ღამის მაღალი ტემპერატურის შესახებ',
  'გაფრთხილება ჰაერის დაბალი ტემპერატურის შესახებ',
  'გაფრთხილება ადრეული წაყინვის შესახებ',
  'გაფრთხილება გვიანი წაყინვის შესახებ',
  'გაფრთხილება ნისლის შესახებ',
  'გაფრთხილება ღვარცოფის შესახებ',
  'რეკომენდაცია მეწყრის საფრთხის შესახებ',
  'გაფრთხილება მეწყრის საფრთხის შესახებ',
  'გაფრთხილება ჰაერის ხარისხის შესახებ',
  'გაფრთხილება ულტრაიისფერი გამოსხივების მაღალი დონის შესახებ',
  'გაფრთხილება შტორმული ღელვის შესახებ',
  'გაფრთხილება ზღვაზე შტორმის შესახებ',

  // do not delete
  'wind',
  'seaWind',

] as const;

export const severityList = ['', 'Moderate', 'Severe', 'Extreme'] as const;
